FROM jenkins/jenkins:lts
USER root

# Install Eclipse Temurin (OpenJDK)
RUN apt-get update && \
    apt-get install -y wget software-properties-common && \
    wget https://adoptium.net/installation/linux/ && \
    bash install_temurin_jdk.sh

# Install Docker CLI
RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh

USER jenkins
