version: '3.8'
services:
  jenkins:
    container_name: custom-jenkins
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /c/Users/Student/jenkins:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
